version: '3'

services:

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: files

  web-app:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
        - mysqldb
    volumes:
      - .:/code
    restart: on-failure