version: '3'

services:
  web-app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - fw-mysql
    depends_on:
        - mysqldb
    volumes:
      - .:/code

  mysqldb:
    image: mysql:8
    networks:
      - fw-mysql
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: files
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  fw-mysql: