version: '3'

services:

  mysqldb:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: files
    ports:
      - "3308:3306"

  web-app:
    build: .
    image: mihaialexandruteodor/featherwriter
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
        - mysqldb
    volumes:
      - .:/code
    restart: on-failure