apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web-app
    spec:
      containers:
        - image: mihaialexandruteodor/featherwriter
          name: web-app
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: web-app-claim0
      restartPolicy: Always
      volumes:
        - name: web-app-claim0
          persistentVolumeClaim:
            claimName: web-app-claim0
status: {}
