apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  creationTimestamp: null
  labels:
    io.kompose.service: web-app
  name: web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: web-app
    tier: frontend
