spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 364060468579-9cbk5fvihqfqmrs4h6lj1fd3egj7k084.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile