spring:
  datasource:
    password: helloworld
    url: jdbc:mysql://mysqldb:3306/files?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&jdbcCompliantTruncation=false
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 364060468579-9cbk5fvihqfqmrs4h6lj1fd3egj7k084.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile